# Generated by Django 3.2 on 2021-04-15 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210415_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='action',
            field=models.CharField(blank=True, choices=[('b', 'Buy'), ('s', 'Sell')], default='b', help_text='Transaction type:,', max_length=1),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this transaction', primary_key=True, serialize=False),
        ),
    ]
