# Generated by Django 3.2 on 2021-04-22 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cryptocurrency', to_field='symbol'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cryptocurrency', to_field='symbol'),
        ),
    ]
